services:
  postgres:
    image: postgres:latest
    container_name: filmoteka_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: matyyy
      POSTGRES_PASSWORD: matyyy1234
      POSTGRES_DB: filmoteka
    ports:
      - "${PORT}:5432"
    volumes:
      - ./Docker/pgdata:/var/lib/postgresql
      - ./schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./seed.sql:/docker-entrypoint-initdb.d/02_seed.sql